POST {{ host }}/login
Content-Type: application/json

{
    "name": "{{ admin_user }}",
    "password": "{{ admin_pass }}"
}

> {%
client.global.set("token", response.body.token);
%}

###

GET {{ host }}/stats/doctors
Accept: text/csv
Authorization: Bearer {{token}}
